### ISSUE TITLE
How Saving Works...

### ISSUE THREAD

**Issue by crvogt** [clockworksoul/docker-zork2#1]
Hi there!
I've managed to save a game (as far as I can tell) but not sure how to load it again... How would I do that?
I tried docker run -it -v ~/saves/zork2:/saved_game clockworksoul/zork2 but it just starts a new game each time.
Thanks!

**Comment by clockworksoul** [comment]
Hi!

All loads and saves are done using the SAVE and RESTORE commands in-game. 

Always keep the docker volume parameters the same. 🙂

Best,

Matt

**Comment by crvogt** [comment]
Aaah, restore!

Awesome, thank you!
